<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
الماس

</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این مسئله از داده‌های یک فروشگاه الماس که شامل اطلاعات مختلف الماس‌ها (وزن به قیراط،‌ طول، عرض، ارتفاع و غیره) است استفاده خواهیم کرد و ساخت دیتاسری و دیتافریم پانداز را با همدیگر تمرین خواهیم کرد.

</font>
</p>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
import os
os.chdir('/content/drive/MyDrive/ML/DataMining')

In [ ]:
pip list

Package                               Version
------------------------------------- -------------------
absl-py                               1.4.0
accelerate                            1.9.0
aiofiles                              24.1.0
aiohappyeyeballs                      2.6.1
aiohttp                               3.11.15
aiosignal                             1.4.0
alabaster                             1.0.0
albucore                              0.0.24
albumentations                        2.0.8
ale-py                                0.11.2
altair                                5.5.0
annotated-types                       0.7.0
antlr4-python3-runtime                4.9.3
anyio                                 4.9.0
argon2-cffi                           25.1.0
argon2-cffi-bindings                  21.2.0
array_record                          0.7.2
arviz                                 0.22.0
astropy                               7.1.0
astropy-iers-data                     0.2025.7.14.0.40.29
astunparse                            1.6.3
atpublic                              5.1
attrs                                 25.3.0
audioread                             3.0.1
autograd                              1.8.0
babel                                 2.17.0
backcall                              0.2.0
backports.tarfile                     1.2.0
beautifulsoup4                        4.13.4
betterproto                           2.0.0b6
bigframes                             2.11.0
bigquery-magics                       0.10.1
bleach                                6.2.0
blinker                               1.9.0
blis                                  1.3.0
blobfile                              3.0.0
blosc2                                3.6.1
bokeh                                 3.7.3
Bottleneck                            1.4.2
bqplot                                0.12.45
branca                                0.8.1
Brotli                                1.1.0
build                                 1.2.2.post1
CacheControl                          0.14.3
cachetools                            5.5.2
catalogue                             2.0.10
certifi                               2025.7.14
cffi                                  1.17.1
chardet                               5.2.0
charset-normalizer                    3.4.2
chex                                  0.1.89
clarabel                              0.11.1
click                                 8.2.1
cloudpathlib                          0.21.1
cloudpickle                           3.1.1
cmake                                 3.31.6
cmdstanpy                             1.2.5
colorcet                              3.1.0
colorlover                            0.3.0
colour                                0.1.5
community                             1.0.0b1
confection                            0.1.5
cons                                  0.4.7
contourpy                             1.3.2
cramjam                               2.10.0
cryptography                          43.0.3
cuda-python                           12.6.2.post1
cudf-cu12                             25.6.0
cudf-polars-cu12                      25.6.0
cufflinks                             0.17.3
cuml-cu12                             25.6.0
cupy-cuda12x                          13.3.0
curl_cffi                             0.12.0
cuvs-cu12                             25.6.1
cvxopt                                1.3.2
cvxpy                                 1.6.7
cycler                                0.12.1
cyipopt                               1.5.0
cymem                                 2.0.11
Cython                                3.0.12
dask                                  2025.5.0
dask-cuda                             25.6.0
dask-cudf-cu12                        25.6.0
dataproc-spark-connect                0.8.2
datascience                           0.17.6
datasets                              2.14.4
db-dtypes                             1.4.3
dbus-python                           1.2.18
debugpy                               1.8.15
decorator                             4.4.2
defusedxml                            0.7.1
diffusers                             0.34.0
dill                                  0.3.7
distributed                           2025.5.0
distributed-ucxx-cu12                 0.44.0
distro                                1.9.0
dlib                                  19.24.6
dm-tree                               0.1.9
docstring_parser                      0.16
docutils                              0.21.2
dopamine_rl                           4.1.2
duckdb                                1.3.2
earthengine-api                       1.5.24
easydict                              1.13
editdistance                          0.8.1
eerepr                                0.1.2
einops                                0.8.1
en_core_web_sm                        3.8.0
entrypoints                           0.4
et_xmlfile                            2.0.0
etils                                 1.13.0
etuples                               0.3.10
Farama-Notifications                  0.0.4
fastai                                2.7.19
fastapi                               0.116.1
fastcore                              1.7.29
fastdownload                          0.0.7
fastjsonschema                        2.21.1
fastprogress                          1.0.3
fastrlock                             0.8.3
ffmpy                                 0.6.0
filelock                              3.18.0
firebase-admin                        6.9.0
Flask                                 3.1.1
flatbuffers                           25.2.10
flax                                  0.10.6
folium                                0.20.0
fonttools                             4.59.0
frozendict                            2.4.6
frozenlist                            1.7.0
fsspec                                2025.7.0
future                                1.0.0
gast                                  0.6.0
gcsfs                                 2025.7.0
GDAL                                  3.8.4
gdown                                 5.2.0
geemap                                0.35.3
geocoder                              1.38.1
geographiclib                         2.0
geopandas                             1.1.1
geopy                                 2.4.1
gin-config                            0.5.0
gitdb                                 4.0.12
GitPython                             3.1.44
glob2                                 0.7
google                                2.0.3
google-ai-generativelanguage          0.6.15
google-api-core                       2.25.1
google-api-python-client              2.176.0
google-auth                           2.38.0
google-auth-httplib2                  0.2.0
google-auth-oauthlib                  1.2.2
google-cloud-aiplatform               1.104.0
google-cloud-bigquery                 3.35.0
google-cloud-bigquery-connection      1.18.3
google-cloud-bigquery-storage         2.32.0
google-cloud-core                     2.4.3
google-cloud-dataproc                 5.21.0
google-cloud-datastore                2.21.0
google-cloud-firestore                2.21.0
google-cloud-functions                1.20.4
google-cloud-iam                      2.19.1
google-cloud-language                 2.17.2
google-cloud-resource-manager         1.14.2
google-cloud-spanner                  3.55.0
google-cloud-storage                  2.19.0
google-cloud-translate                3.21.1
google-colab                          1.0.0
google-crc32c                         1.7.1
google-genai                          1.26.0
google-generativeai                   0.8.5
google-pasta                          0.2.0
google-resumable-media                2.7.2
googleapis-common-protos              1.70.0
googledrivedownloader                 1.1.0
gradio                                5.38.0
gradio_client                         1.11.0
graphviz                              0.21
greenlet                              3.2.3
groovy                                0.1.2
grpc-google-iam-v1                    0.14.2
grpc-interceptor                      0.15.4
grpcio                                1.73.1
grpcio-status                         1.71.2
grpclib                               0.4.8
gspread                               6.2.1
gspread-dataframe                     4.0.0
gym                                   0.25.2
gym-notices                           0.0.8
gymnasium                             1.2.0
h11                                   0.16.0
h2                                    4.2.0
h5netcdf                              1.6.3
h5py                                  3.14.0
hdbscan                               0.8.40
hf_transfer                           0.1.9
hf-xet                                1.1.5
highspy                               1.11.0
holidays                              0.76
holoviews                             1.21.0
hpack                                 4.1.0
html5lib                              1.1
httpcore                              1.0.9
httpimport                            1.4.1
httplib2                              0.22.0
httpx                                 0.28.1
huggingface-hub                       0.33.4
humanize                              4.12.3
hyperframe                            6.1.0
hyperopt                              0.2.7
ibis-framework                        9.5.0
idna                                  3.10
imageio                               2.37.0
imageio-ffmpeg                        0.6.0
imagesize                             1.4.1
imbalanced-learn                      0.13.0
immutabledict                         4.2.1
importlib_metadata                    8.7.0
importlib_resources                   6.5.2
imutils                               0.5.4
inflect                               7.5.0
iniconfig                             2.1.0
intel-cmplr-lib-ur                    2025.2.0
intel-openmp                          2025.2.0
ipyevents                             2.0.2
ipyfilechooser                        0.6.0
ipykernel                             6.17.1
ipyleaflet                            0.20.0
ipyparallel                           8.8.0
ipython                               7.34.0
ipython-genutils                      0.2.0
ipython-sql                           0.5.0
ipytree                               0.2.2
ipywidgets                            7.7.1
itsdangerous                          2.2.0
jaraco.classes                        3.4.0
jaraco.context                        6.0.1
jaraco.functools                      4.2.1
jax                                   0.5.2
jax-cuda12-pjrt                       0.5.1
jax-cuda12-plugin                     0.5.1
jaxlib                                0.5.1
jeepney                               0.9.0
jieba                                 0.42.1
Jinja2                                3.1.6
jiter                                 0.10.0
joblib                                1.5.1
jsonpatch                             1.33
jsonpickle                            4.1.1
jsonpointer                           3.0.0
jsonschema                            4.25.0
jsonschema-specifications             2025.4.1
jupyter-client                        6.1.12
jupyter-console                       6.1.0
jupyter_core                          5.8.1
jupyter_kernel_gateway                2.5.2
jupyter-leaflet                       0.20.0
jupyter-server                        1.16.0
jupyterlab_pygments                   0.3.0
jupyterlab_widgets                    3.0.15
jupytext                              1.17.2
kaggle                                1.7.4.5
kagglehub                             0.3.12
keras                                 3.8.0
keras-hub                             0.18.1
keras-nlp                             0.18.1
keyring                               25.6.0
keyrings.google-artifactregistry-auth 1.1.2
kiwisolver                            1.4.8
langchain                             0.3.26
langchain-core                        0.3.69
langchain-text-splitters              0.3.8
langcodes                             3.5.0
langsmith                             0.4.7
language_data                         1.3.0
launchpadlib                          1.10.16
lazr.restfulclient                    0.14.4
lazr.uri                              1.0.6
lazy_loader                           0.4
libclang                              18.1.1
libcudf-cu12                          25.6.0
libcugraph-cu12                       25.6.0
libcuml-cu12                          25.6.0
libcuvs-cu12                          25.6.1
libkvikio-cu12                        25.6.0
libpysal                              4.13.0
libraft-cu12                          25.6.0
librmm-cu12                           25.6.0
librosa                               0.11.0
libucx-cu12                           1.18.1
libucxx-cu12                          0.44.0
lightgbm                              4.6.0
linkify-it-py                         2.0.3
llvmlite                              0.43.0
locket                                1.0.0
logical-unification                   0.4.6
lxml                                  5.4.0
Mako                                  1.1.3
marisa-trie                           1.2.1
Markdown                              3.8.2
markdown-it-py                        3.0.0
MarkupSafe                            3.0.2
matplotlib                            3.10.0
matplotlib-inline                     0.1.7
matplotlib-venn                       1.1.2
mdit-py-plugins                       0.4.2
mdurl                                 0.1.2
miniKanren                            1.0.3
missingno                             0.5.2
mistune                               3.1.3
mizani                                0.13.5
mkl                                   2025.2.0
ml-dtypes                             0.4.1
mlxtend                               0.23.4
more-itertools                        10.7.0
moviepy                               1.0.3
mpmath                                1.3.0
msgpack                               1.1.1
multidict                             6.6.3
multipledispatch                      1.0.0
multiprocess                          0.70.15
multitasking                          0.0.11
murmurhash                            1.0.13
music21                               9.3.0
namex                                 0.1.0
narwhals                              1.47.1
natsort                               8.4.0
nbclassic                             1.3.1
nbclient                              0.10.2
nbconvert                             7.16.6
nbformat                              5.10.4
ndindex                               1.10.0
nest-asyncio                          1.6.0
networkx                              3.5
nibabel                               5.3.2
nltk                                  3.9.1
notebook                              6.5.7
notebook_shim                         0.2.4
numba                                 0.60.0
numba-cuda                            0.11.0
numexpr                               2.11.0
numpy                                 2.0.2
nvidia-cublas-cu12                    12.5.3.2
nvidia-cuda-cupti-cu12                12.5.82
nvidia-cuda-nvcc-cu12                 12.5.82
nvidia-cuda-nvrtc-cu12                12.5.82
nvidia-cuda-runtime-cu12              12.5.82
nvidia-cudnn-cu12                     9.3.0.75
nvidia-cufft-cu12                     11.2.3.61
nvidia-curand-cu12                    10.3.6.82
nvidia-cusolver-cu12                  11.6.3.83
nvidia-cusparse-cu12                  12.5.1.3
nvidia-cusparselt-cu12                0.6.2
nvidia-ml-py                          12.575.51
nvidia-nccl-cu12                      2.21.5
nvidia-nvjitlink-cu12                 12.5.82
nvidia-nvtx-cu12                      12.4.127
nvtx                                  0.2.12
nx-cugraph-cu12                       25.6.0
oauth2client                          4.1.3
oauthlib                              3.3.1
omegaconf                             2.3.0
openai                                1.97.0
opencv-contrib-python                 4.12.0.88
opencv-python                         4.12.0.88
opencv-python-headless                4.12.0.88
openpyxl                              3.1.5
opt_einsum                            3.4.0
optax                                 0.2.5
optree                                0.16.0
orbax-checkpoint                      0.11.16
orjson                                3.11.0
osqp                                  1.0.4
packaging                             25.0
pandas                                2.2.2
pandas-datareader                     0.10.0
pandas-gbq                            0.29.2
pandas-stubs                          2.2.2.240909
pandocfilters                         1.5.1
panel                                 1.7.4
param                                 2.2.1
parso                                 0.8.4
parsy                                 2.1
partd                                 1.4.2
pathlib                               1.0.1
patsy                                 1.0.1
peewee                                3.18.2
peft                                  0.16.0
pexpect                               4.9.0
pickleshare                           0.7.5
pillow                                11.3.0
pip                                   24.1.2
platformdirs                          4.3.8
plotly                                5.24.1
plotnine                              0.14.5
pluggy                                1.6.0
ply                                   3.11
polars                                1.25.0
pooch                                 1.8.2
portpicker                            1.5.2
preshed                               3.0.10
prettytable                           3.16.0
proglog                               0.1.12
progressbar2                          4.5.0
prometheus_client                     0.22.1
promise                               2.3
prompt_toolkit                        3.0.51
propcache                             0.3.2
prophet                               1.1.7
proto-plus                            1.26.1
protobuf                              5.29.5
psutil                                5.9.5
psycopg2                              2.9.10
ptyprocess                            0.7.0
py-cpuinfo                            9.0.0
py4j                                  0.10.9.7
pyarrow                               18.1.0
pyasn1                                0.6.1
pyasn1_modules                        0.4.2
pycairo                               1.28.0
pycocotools                           2.0.10
pycparser                             2.22
pycryptodomex                         3.23.0
pydantic                              2.11.7
pydantic_core                         2.33.2
pydata-google-auth                    1.9.1
pydot                                 3.0.4
pydotplus                             2.0.2
PyDrive                               1.3.1
PyDrive2                              1.21.3
pydub                                 0.25.1
pyerfa                                2.0.1.5
pygame                                2.6.1
pygit2                                1.18.0
Pygments                              2.19.2
PyGObject                             3.42.0
PyJWT                                 2.10.1
pylibcudf-cu12                        25.6.0
pylibcugraph-cu12                     25.6.0
pylibraft-cu12                        25.6.0
pymc                                  5.24.0
pymystem3                             0.2.0
pynndescent                           0.5.13
pynvjitlink-cu12                      0.7.0
pynvml                                12.0.0

In [ ]:
pip uninstall pandas

Found existing installation: pandas 2.2.2
Uninstalling pandas-2.2.2:
  Would remove:
    /usr/local/lib/python3.11/dist-packages/pandas-2.2.2.dist-info/*
    /usr/local/lib/python3.11/dist-packages/pandas/*
Proceed (Y/n)?

In [ ]:
pip install pandas==1.3.1

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت اول:
برش ایده‌آل
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
برای بررسی کیفیت برش الماس‌ها از یک کارشناس کمک خواستیم و او کیفیت هر الماس را در یک لیست نوشته و لیست نهایی زیر را به ما تحویل داده است:
  
</font>
</p>

In [ ]:
cut = ['Ideal', 'Premium', 'Premium', 'Premium', 'Premium', 'Very Good',
       'Premium', 'Premium', 'Ideal', 'Premium', 'Good', 'Good', 'Premium',
       'Very Good', 'Very Good', 'Good', 'Good','Very Good', 'Good', 'Good',
       'Premium', 'Premium', 'Good', 'Good']

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
با استفاده از این اطلاعات، یک دیتاسری به نام <code>cut_series</code> بسازید.
</font>
</p>

In [ ]:
import pandas as pd
cut_series = pd.Series(cut)
cut_series

0         Ideal
1       Premium
2       Premium
3       Premium
4       Premium
5     Very Good
6       Premium
7       Premium
8         Ideal
9       Premium
10         Good
11         Good
12      Premium
13    Very Good
14    Very Good
15         Good
16         Good
17    Very Good
18         Good
19         Good
20      Premium
21      Premium
22         Good
23         Good
dtype: object

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در دیتاسری <code>cut_series</code>، کیفیت برش هر الماس ذخیره شده است. حال تعداد هر کیفیت برش را به‌شکل <b>صعودی</b> در یک دیتاسری جدید به نام <code>cut_sorted</code> ذخیره کنید. یعنی عنوان و تعداد کم‌ تعداد‌ترین نوع برش، باید در ابتدای این دیتاسری قرار بگیرد.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
برای ساخت این دیتاسری، باید از یکی از توابع معرفی‌شده در درسنامه‌ی «بررسی دیتافریم» استفاده کنید.
</font>
</p>

In [ ]:
cut_values = cut_series.value_counts()
cut_values

Premium      10
Good          8
Very Good     4
Ideal         2
Name: count, dtype: int64

In [ ]:
# sort the values in descending order
cut_sorted = cut_values.sort_values(ascending = True)
cut_sorted

Ideal         2
Very Good     4
Good          8
Premium      10
Name: count, dtype: int64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت دوم:
قیراط الماس‌ها
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
 با استفاده از ترازو الماس‌ها را وزن کرده و حاصل را در لیست زیر قرار داده‌ایم.
</font>
</p>

In [ ]:
carat = [1.07, 1.19, 1.19, 1.2, 1.2, 1.25, 1.2, 1.2, 1.2,
         1.14, 1.01, 1.01, 1.01, 1.02, 1.01, 1.01, 1.01,
         1.01, 1.01, 1.01, 1.01, 1.01, 1.0, 1.0]

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
با استفاده از این اطلاعات، یک دیتاسری به نام <code>carat_series</code> بسازید.

</font>
</p>

In [ ]:
carat_series = pd.Series(carat)
carat_series

0     1.07
1     1.19
2     1.19
3     1.20
4     1.20
5     1.25
6     1.20
7     1.20
8     1.20
9     1.14
10    1.01
11    1.01
12    1.01
13    1.02
14    1.01
15    1.01
16    1.01
17    1.01
18    1.01
19    1.01
20    1.01
21    1.01
22    1.00
23    1.00
dtype: float64

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در فصل نامپای با صدک‌ها آشنا شدید. صدک هفتاد و پنجم این دیتاسری را محاسبه کنید و در متغیر <code>carat_75</code> ذخیره کنید.
</font>
</p>

In [ ]:
import numpy as np
carat_75 = np.percentile(carat_series, 75)
carat_75

np.float64(1.1925)

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت سوم:
ابعاد الماس
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
در این مرحله از یک کارشناس دیگر خواستیم که الماس‌ها را اندازه‌گیری کند و او یک آرایه‌ی نامپای به ما تحویل داده است.
<br>
یکی از راه‌های ذخیره‌سازی آرایه‌ی نامپای، استفاده از فرمت ذخیره‌سازی <code>npz</code> است. در این فایل می‌توان هر تعداد آرایه‌ی نامپای را ذخیره کرد و بعد با استفاده از نام آرایه‌ها، آرایه‌ی مورد نظر را از فایل بیرون کشید. برای آشنایی بیشتر با این فرمت می‌توانید
<a href="https://stackoverflow.com/questions/54238670/what-is-the-advantage-of-saving-npz-files-instead-of-npy-in-python-regard">
 این لینک
</a>
 را مطالعه کنید.
<br>
چون نحوه‌ی استفاده این فایل را برای شما توضیح نداده‌ایم، کد خواندن این فایل و سپس بیرون کشیدن آرایه‌ی <code>sizes</code> از آن را در سلول زیر برای شما نوشته‌ایم. آرایه‌ی حاصل در متغیری به نام <code>sizes_array</code> ذخیره می‌شود.

</font>
</p>

In [ ]:
import numpy as np

sizes = np.load('/content/drive/MyDrive/ML/DataMining/الماس/sizes.npz', allow_pickle=True)
sizes_array = sizes['sizes']
sizes_array

array([[6.46, 6.42, 4.09],
       [6.87, 6.84, 4.17],
       [6.73, 6.66, 4.2],
       [6.77, 6.72, 4.22],
       [6.77, 6.72, 4.22],
       [6.86, 6.9, 4.27],
       [6.93, 6.8, 4.24],
       [6.86, 6.74, 4.21],
       [6.73, 6.68, 4.24],
       [6.76, 6.72, 4.13],
       [6.19, 6.23, 4.05],
       [6.48, 6.5, 3.79],
       [6.46, 6.41, 3.94],
       [6.34, 6.41, 4.06],
       [6.35, 6.3, 4.0],
       [6.35, 6.3, 4.02],
       [6.37, 6.31, 4.05],
       [6.39, 6.34, 4.02],
       [6.4, 6.32, 4.05],
       [6.58, 6.53, 3.77],
       [6.46, 6.37, 3.92],
       [6.44, 6.38, 3.95],
       [6.33, 6.38, 4.01],
       [6.27, 6.31, 3.99]], dtype=object)


<p dir=rtl style="direction: rtl;text-align: right;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
 آرایه‌ی <code>sizes_array</code> دارای سه ستون است. در ستون اول طول، در ستون دوم عرض و در ستون سوم ارتفاع الماس‌ها ذخیره شده است.
 <br>
با استفاده از این آرایه، یک دیتافریم به نام <code>sizes_df</code> بسازید و نام ستون‌های آن را برابر <code>x</code> , <code>y</code> , <code>z</code> قرار دهید. (اولین ستون <code>x</code> نام دارد).
 </font>
</p>

In [ ]:
# Create the pandas DataFrame
sizes_array = sizes_array.astype(float)
sizes_df = pd.DataFrame(sizes_array, columns=['x', 'y', 'z'])
sizes_df

       x     y     z
0   6.46  6.42  4.09
1   6.87  6.84  4.17
2   6.73  6.66  4.20
3   6.77  6.72  4.22
4   6.77  6.72  4.22
5   6.86  6.90  4.27
6   6.93  6.80  4.24
7   6.86  6.74  4.21
8   6.73  6.68  4.24
9   6.76  6.72  4.13
10  6.19  6.23  4.05
11  6.48  6.50  3.79
12  6.46  6.41  3.94
13  6.34  6.41  4.06
14  6.35  6.30  4.00
15  6.35  6.30  4.02
16  6.37  6.31  4.05
17  6.39  6.34  4.02
18  6.40  6.32  4.05
19  6.58  6.53  3.77
20  6.46  6.37  3.92
21  6.44  6.38  3.95
22  6.33  6.38  4.01
23  6.27  6.31  3.99

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
قسمت چهارم:
نمایه‌سازی
</font>
</h2>
<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    برخلاف دنیای برنامه‌نویسان در کسب‌و‌کار الماس مرسوم نیست که شماره‌گذاری از <code>0</code> شروع شود. بنابراین نمایه‌ها را طوری تغییر دهید که از <code>1</code> شروع شوند.  
دیتافریم جدید را در <code>sizes_new_index</code> ذخیره کنید.
<br>

</font>
</p>

In [ ]:
sizes_new_index = sizes_df.copy()

sizes_df.index = np.arange(1, len(sizes_df)+1)
sizes_new_index = pd.DataFrame(sizes_array, index=sizes_df.index, columns=['x', 'y', 'z'])
sizes_new_index

       x     y     z
1   6.46  6.42  4.09
2   6.87  6.84  4.17
3   6.73  6.66  4.20
4   6.77  6.72  4.22
5   6.77  6.72  4.22
6   6.86  6.90  4.27
7   6.93  6.80  4.24
8   6.86  6.74  4.21
9   6.73  6.68  4.24
10  6.76  6.72  4.13
11  6.19  6.23  4.05
12  6.48  6.50  3.79
13  6.46  6.41  3.94
14  6.34  6.41  4.06
15  6.35  6.30  4.00
16  6.35  6.30  4.02
17  6.37  6.31  4.05
18  6.39  6.34  4.02
19  6.40  6.32  4.05
20  6.58  6.53  3.77
21  6.46  6.37  3.92
22  6.44  6.38  3.95
23  6.33  6.38  4.01
24  6.27  6.31  3.99

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zipfile
import joblib

carat_series.to_csv("carat_series.csv")
cut_sorted.to_csv("cut_sorted.csv")
cut_series.to_csv("cut_series.csv")
joblib.dump(carat_75,"carat_75")
sizes_df.to_csv("sizes_df.csv",index = True)
sizes_new_index.to_csv("sizes_new_index.csv",index = True)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["cut_series.csv", "cut_sorted.csv", "carat_series.csv",
              "carat_75", "sizes_df.csv", "sizes_new_index.csv", "diamond.ipynb"]
compress(file_names)

File Paths:
['cut_series.csv', 'cut_sorted.csv', 'carat_series.csv', 'carat_75', 'sizes_df.csv', 'sizes_new_index.csv', 'diamond.ipynb']