<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    یکتانت
</font>
</h1>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
داده‌هایی که در این تمرین استفاده می‌کنیم، داده‌هایی است که شرکت یکتانت از وبسایت‌های مختلف جمع‌آوری کرده است. قصد داریم با بررسی آمار مشاهده‌ی کاربران از وب‌سایت‌ها، درصد شهرت وب‌سایت‌های فارسی با کلید‌واژه‌های پرکاربردتر را محاسبه و بررسی کنیم.
</font>
</p>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import os
os.chdir('/content/drive/MyDrive/ML/DataMining')

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مجموعه‌داده
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
داده‌های این تمرین از طریق فایل <code>yektanet.csv</code> در دسترس شما قرار گرفته است. ابتدا این فایل را خوانده و نگاهی به آن بیندازید. توضیح هرکدام از ستون‌های این مجموعه‌داده در جدول زیر آمده است:
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>

| ستون | توضیح |
| :---: | :---: |
| `keywords` | کلیدواژه‌هایی که هر وب‌سایت با آن‌ها تعریف می‌شود و معمولاً در جست‌و‌جوها با آن موضوع نمایش داده می‌شود. |
| `segments` | دسته‌بندی‌هایی که برای هر وب‌سایت در نظر می‌گیریم و برای تبلیغات استفاده می‌شوند. |
| `visit count` | تعداد بازدیدهای متوسط صفحه در یک روز |

</font>
</div>
</center>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ML/DataMining/یکتانت/yektanet.csv')
df.tail()

,keywords,segments,visit count
219614,"['نتایج زنده', 'نتایج', 'زنده']","['maleSegment', 'varzeshi']",641
219615,"['زیرنویس', 'فارسی فیلم', 'دانلود زیرنویس']",['femaleSegment'],355
219616,"['سامان', 'ساعت']",['femaleSegment'],40
219617,"['چشم', 'تنظیم', 'رنگ', 'نرم']",['technology'],523
219618,"['خارجی', 'قوی', 'ایرانی خارجی', 'ایرانی']",['femaleSegment'],906

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    قسمت اول
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    با استفاده از گروه‌بندی و تابع <code>filter</code>، وب‌سایت‌هایی را انتخاب کنید که کلیدواژه‌ی مربوط به آن‌ها، بیشتر از ۱۴۰۰ وب‌سایت را شامل می‌شود. به بیان دیگر، آن لیست کلیدواژه بیش از ۱۴۰۰ بار در دیتافریم تکرار شده باشد. حاصل را در متغیر <code>filtered_df</code> ذخیره کنید.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
 ابتدا تابع <code>groupby</code> را برای کلید‌واژه‌ها اعمال کرده و سپس از از تابع <code>len</code> برای بررسی تعداد اعضا استفاده کنید. توجه کنید <b> لازم نیست </b>گروه‌بندی براساس هر عضو داخل آرایه‌ی کلیدواژه‌ها انجام شود.
</font>
</p>

In [ ]:
# Filter groups
filtered_df = df.groupby('keywords').filter(lambda x: len(x) > 1400)
filtered_df

,keywords,segments,visit count
1,"['نتایج زنده', 'نتایج', 'زنده']",['maleSegment'],822
3,"['نتایج زنده', 'نتایج', 'زنده']",['maleSegment'],307
4,"['نتایج زنده', 'نتایج', 'زنده']",['maleSegment'],778
10,"['نتایج زنده', 'نتایج', 'زنده']","['maleSegment', 'varzeshi']",418
16,"['نتایج زنده', 'نتایج', 'زنده']",['maleSegment'],324
...,...,...,...
219597,"['صفحه اخبار', 'صفحه', 'اخبار']",['maleSegment'],669
219601,"['نتایج زنده', 'نتایج', 'زنده']",['maleSegment'],742
219608,"['نتایج زنده', 'نتایج', 'زنده']","['salamat', 'laghari']",472
219612,"['نتایج زنده', 'نتایج', 'زنده']",['maleSegment'],460
219614,"['نتایج زنده', 'نتایج', 'زنده']","['maleSegment', 'varzeshi']",641

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
    قسمت دوم
</font>
</h2>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    اکنون ستونی به نام <code>popularity</code> را به دیتافریم <code>filtered_df</code> اضافه کنید که نسبت تعداد بازدید هر وب‌سایت به مجموع تعداد بازدید تمام وب‌سایت‌های آن کلیدواژه را شامل شود.
</font>
</p>

<p dir=rtl style="direction: rtl;text-align: justify;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
<span style="color:green"><b>راهنمایی:</b></span>
بعد از انجام گروه‌بندی بر اساس <code>keywords</code>، تابع <code>transfrom</code> را روی ستون <code>visit count</code> اعمال کرده و نسبت بازید هر وب‌سایت به مجموع بازدیدهای آن گروه کلیدواژه را محاسبه و در ۱۰۰ ضرب کنید.
</font>
</p>

In [ ]:
# Apply Transformation Methods
total_visits_per_key_word = filtered_df.groupby('keywords')['visit count'].transform('sum')
filtered_df['popularity'] = (filtered_df['visit count'] / total_visits_per_key_word) * 100
filtered_df['popularity']

1         0.016966
3         0.006337
4         0.016058
10        0.008628
16        0.006687
            ...
219597    0.014774
219601    0.015315
219608    0.009742
219612    0.009494
219614    0.013230
Name: popularity, Length: 24247, dtype: float64

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>


<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [ ]:
import zlib
import zipfile

filtered_df.to_csv('filtered_df.csv', index=True)

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

file_names = ["filtered_df.csv", "yektanet.ipynb"]
compress(file_names)

File Paths:
['filtered_df.csv', 'yektanet.ipynb']